# detection parameters (tweak anytime)
min_profit_bps: 70         # 0.70% after fees/slippage
slippage_bps: 10           # cushion for fills
poll_ms: 500               # REST polling cadence per symbol per exchange
log_dir: "./logs"
out_dir: "./out"
symbols:                   # AUD focus
  - BTC/AUD
  - ETH/AUD
  - SOL/AUD
  - XRP/AUD
  - ADA/AUD
  - MATIC/AUD
  - LINK/AUD
  - DOT/AUD
  - AVAX/AUD
  - LTC/AUD
  - DOGE/AUD
  - SHIB/AUD
exchanges:                 # CCXT ids
  - kraken
  - independentreserve
  - btcmarkets
  - okx
  - coinspot
fees_bps:                  # conservative taker assumptions (override later)
  kraken: 26               # 0.26%
  independentreserve: 50   # 0.50%
  btcmarkets: 35           # 0.35% (mid of schedule)
  okx: 10                  # 0.10% (tiered; adjust per acct)
  coinspot: 100            # 1.00% retail; adjust if eligible for lower
# note: Swyftx is not in CCXT; integrate later via their JWT API if needed.
