# detection parameters (tweak anytime)
max_trade_aud: 250
min_profit_bps: 70         # 0.70% after fees/slippage
slippage_bps: 10           # cushion for fills
poll_ms: 500               # REST/Web poll cadence per symbol per exchange (ms)
log_dir: "./logs"
out_dir: "./out"

# AUD focus
symbols:
  - BTC/AUD
  - ETH/AUD
  - SOL/AUD
  - XRP/AUD
  - ADA/AUD
  - MATIC/AUD
  - LINK/AUD
  - DOT/AUD
  - AVAX/AUD
  - LTC/AUD
  - DOGE/AUD
  - SHIB/AUD

# Exchanges (CCXT + custom swyftx)
exchanges:
  - kraken
  - independentreserve
  - btcmarkets
  - okx
  - coinspot
  - swyftx

# conservative taker fee assumptions (bps)
fees_bps:
  kraken: 26
  independentreserve: 50
  btcmarkets: 35
  okx: 10
  coinspot: 100
  swyftx: 100
