# detection parameters (tweak anytime)
max_trade_aud: 250
min_profit_bps: 50         # 0.50% after fees/slippage
slippage_bps: 10
poll_ms: 500
log_dir: "./logs"
out_dir: "./out"

# AUD focus (+ memes)
symbols:
  - BTC/AUD
  - ETH/AUD
  - SOL/AUD
  - XRP/AUD
  - ADA/AUD
  - MATIC/AUD
  - LINK/AUD
  - DOT/AUD
  - AVAX/AUD
  - LTC/AUD
  - DOGE/AUD
  - SHIB/AUD
  - PEPE/AUD

# Exchanges (CCXT + custom swyftx, OKX via WS)
exchanges:
  - kraken
  - independentreserve
  - btcmarkets
  - okx
  - coinspot
  - swyftx

# taker fee assumptions (bps) — edit to match the account's tier
fees_bps:
  coinspot: 10           # 0.10%
  swyftx: 60             # 0.60%
  kraken: 40             # 0.40%
  okx: 50                # 0.50% (set 10 if using OKX base taker 0.10%)
  btcmarkets: 85         # 0.85%
  independentreserve: 50 # 0.50%
